{
  "uid" : "5cf573e956b254dd",
  "name" : "Contact Us Form",
  "fullName" : "tests.customer_support_feature_test.TestContactUsFeature#test_contact_us_form",
  "historyId" : "e65723a6056ad021773889a9622c5514",
  "time" : {
    "start" : 1707064639938,
    "stop" : 1707064639938,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'os' is not defined. Did you forget to import 'os'",
  "statusTrace" : "request = <SubRequest 'browser' for <Function test_contact_us_form>>\n\n    @pytest.fixture(scope=\"function\", autouse=True)\n    def browser(request):\n        # preferences = {\"download.default_directory\": \"/usr/workspace/pages/resources\"}\n>       download_folder = os.path.join(os.getcwd(), 'pages', 'resources')\nE       NameError: name 'os' is not defined. Did you forget to import 'os'\n\nconftest.py:9: NameError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "browser",
    "time" : {
      "start" : 1707064640014,
      "stop" : 1707064640014,
      "duration" : 0
    },
    "status" : "broken",
    "statusMessage" : "NameError: name 'os' is not defined. Did you forget to import 'os'\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 9, in browser\n    download_folder = os.path.join(os.getcwd(), 'pages', 'resources')\n                      ^^\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : true,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1707064639939,
      "stop" : 1707064640014,
      "duration" : 75
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "Customer Support"
  }, {
    "name" : "tag",
    "value" : "TestCaseID: 6"
  }, {
    "name" : "severity",
    "value" : "critical"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "customer_support_feature_test"
  }, {
    "name" : "subSuite",
    "value" : "TestContactUsFeature"
  }, {
    "name" : "host",
    "value" : "95e4d765c464"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.customer_support_feature_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "critical",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "TestCaseID: 6" ]
  },
  "source" : "5cf573e956b254dd.json",
  "parameterValues" : [ ]
}